// Country list with flag emoji + bilingual names.
// Value stored in DB is the English name (stable, readable).
export const countries = [
  { code: 'AF', flag: '🇦🇫', en: 'Afghanistan', es: 'Afganistán' },
  { code: 'AL', flag: '🇦🇱', en: 'Albania', es: 'Albania' },
  { code: 'DZ', flag: '🇩🇿', en: 'Algeria', es: 'Argelia' },
  { code: 'AR', flag: '🇦🇷', en: 'Argentina', es: 'Argentina' },
  { code: 'AM', flag: '🇦🇲', en: 'Armenia', es: 'Armenia' },
  { code: 'AU', flag: '🇦🇺', en: 'Australia', es: 'Australia' },
  { code: 'AT', flag: '🇦🇹', en: 'Austria', es: 'Austria' },
  { code: 'AZ', flag: '🇦🇿', en: 'Azerbaijan', es: 'Azerbaiyán' },
  { code: 'BE', flag: '🇧🇪', en: 'Belgium', es: 'Bélgica' },
  { code: 'BO', flag: '🇧🇴', en: 'Bolivia', es: 'Bolivia' },
  { code: 'BA', flag: '🇧🇦', en: 'Bosnia and Herzegovina', es: 'Bosnia y Herzegovina' },
  { code: 'BR', flag: '🇧🇷', en: 'Brazil', es: 'Brasil' },
  { code: 'BG', flag: '🇧🇬', en: 'Bulgaria', es: 'Bulgaria' },
  { code: 'CA', flag: '🇨🇦', en: 'Canada', es: 'Canadá' },
  { code: 'CL', flag: '🇨🇱', en: 'Chile', es: 'Chile' },
  { code: 'CN', flag: '🇨🇳', en: 'China', es: 'China' },
  { code: 'CO', flag: '🇨🇴', en: 'Colombia', es: 'Colombia' },
  { code: 'CR', flag: '🇨🇷', en: 'Costa Rica', es: 'Costa Rica' },
  { code: 'HR', flag: '🇭🇷', en: 'Croatia', es: 'Croacia' },
  { code: 'CU', flag: '🇨🇺', en: 'Cuba', es: 'Cuba' },
  { code: 'CY', flag: '🇨🇾', en: 'Cyprus', es: 'Chipre' },
  { code: 'CZ', flag: '🇨🇿', en: 'Czech Republic', es: 'República Checa' },
  { code: 'DK', flag: '🇩🇰', en: 'Denmark', es: 'Dinamarca' },
  { code: 'DO', flag: '🇩🇴', en: 'Dominican Republic', es: 'República Dominicana' },
  { code: 'EC', flag: '🇪🇨', en: 'Ecuador', es: 'Ecuador' },
  { code: 'EG', flag: '🇪🇬', en: 'Egypt', es: 'Egipto' },
  { code: 'SV', flag: '🇸🇻', en: 'El Salvador', es: 'El Salvador' },
  { code: 'EE', flag: '🇪🇪', en: 'Estonia', es: 'Estonia' },
  { code: 'FI', flag: '🇫🇮', en: 'Finland', es: 'Finlandia' },
  { code: 'FR', flag: '🇫🇷', en: 'France', es: 'Francia' },
  { code: 'GE', flag: '🇬🇪', en: 'Georgia', es: 'Georgia' },
  { code: 'DE', flag: '🇩🇪', en: 'Germany', es: 'Alemania' },
  { code: 'GH', flag: '🇬🇭', en: 'Ghana', es: 'Ghana' },
  { code: 'GR', flag: '🇬🇷', en: 'Greece', es: 'Grecia' },
  { code: 'GT', flag: '🇬🇹', en: 'Guatemala', es: 'Guatemala' },
  { code: 'HN', flag: '🇭🇳', en: 'Honduras', es: 'Honduras' },
  { code: 'HK', flag: '🇭🇰', en: 'Hong Kong', es: 'Hong Kong' },
  { code: 'HU', flag: '🇭🇺', en: 'Hungary', es: 'Hungría' },
  { code: 'IS', flag: '🇮🇸', en: 'Iceland', es: 'Islandia' },
  { code: 'IN', flag: '🇮🇳', en: 'India', es: 'India' },
  { code: 'ID', flag: '🇮🇩', en: 'Indonesia', es: 'Indonesia' },
  { code: 'IE', flag: '🇮🇪', en: 'Ireland', es: 'Irlanda' },
  { code: 'IL', flag: '🇮🇱', en: 'Israel', es: 'Israel' },
  { code: 'IT', flag: '🇮🇹', en: 'Italy', es: 'Italia' },
  { code: 'JP', flag: '🇯🇵', en: 'Japan', es: 'Japón' },
  { code: 'JO', flag: '🇯🇴', en: 'Jordan', es: 'Jordania' },
  { code: 'KZ', flag: '🇰🇿', en: 'Kazakhstan', es: 'Kazajistán' },
  { code: 'KE', flag: '🇰🇪', en: 'Kenya', es: 'Kenia' },
  { code: 'KR', flag: '🇰🇷', en: 'South Korea', es: 'Corea del Sur' },
  { code: 'KW', flag: '🇰🇼', en: 'Kuwait', es: 'Kuwait' },
  { code: 'LV', flag: '🇱🇻', en: 'Latvia', es: 'Letonia' },
  { code: 'LB', flag: '🇱🇧', en: 'Lebanon', es: 'Líbano' },
  { code: 'LT', flag: '🇱🇹', en: 'Lithuania', es: 'Lituania' },
  { code: 'LU', flag: '🇱🇺', en: 'Luxembourg', es: 'Luxemburgo' },
  { code: 'MY', flag: '🇲🇾', en: 'Malaysia', es: 'Malasia' },
  { code: 'MX', flag: '🇲🇽', en: 'Mexico', es: 'México' },
  { code: 'MA', flag: '🇲🇦', en: 'Morocco', es: 'Marruecos' },
  { code: 'NL', flag: '🇳🇱', en: 'Netherlands', es: 'Países Bajos' },
  { code: 'NZ', flag: '🇳🇿', en: 'New Zealand', es: 'Nueva Zelanda' },
  { code: 'NI', flag: '🇳🇮', en: 'Nicaragua', es: 'Nicaragua' },
  { code: 'NG', flag: '🇳🇬', en: 'Nigeria', es: 'Nigeria' },
  { code: 'NO', flag: '🇳🇴', en: 'Norway', es: 'Noruega' },
  { code: 'PK', flag: '🇵🇰', en: 'Pakistan', es: 'Pakistán' },
  { code: 'PA', flag: '🇵🇦', en: 'Panama', es: 'Panamá' },
  { code: 'PY', flag: '🇵🇾', en: 'Paraguay', es: 'Paraguay' },
  { code: 'PE', flag: '🇵🇪', en: 'Peru', es: 'Perú' },
  { code: 'PH', flag: '🇵🇭', en: 'Philippines', es: 'Filipinas' },
  { code: 'PL', flag: '🇵🇱', en: 'Poland', es: 'Polonia' },
  { code: 'PT', flag: '🇵🇹', en: 'Portugal', es: 'Portugal' },
  { code: 'PR', flag: '🇵🇷', en: 'Puerto Rico', es: 'Puerto Rico' },
  { code: 'QA', flag: '🇶🇦', en: 'Qatar', es: 'Qatar' },
  { code: 'RO', flag: '🇷🇴', en: 'Romania', es: 'Rumanía' },
  { code: 'RU', flag: '🇷🇺', en: 'Russia', es: 'Rusia' },
  { code: 'SA', flag: '🇸🇦', en: 'Saudi Arabia', es: 'Arabia Saudita' },
  { code: 'RS', flag: '🇷🇸', en: 'Serbia', es: 'Serbia' },
  { code: 'SG', flag: '🇸🇬', en: 'Singapore', es: 'Singapur' },
  { code: 'SK', flag: '🇸🇰', en: 'Slovakia', es: 'Eslovaquia' },
  { code: 'SI', flag: '🇸🇮', en: 'Slovenia', es: 'Eslovenia' },
  { code: 'ZA', flag: '🇿🇦', en: 'South Africa', es: 'Sudáfrica' },
  { code: 'ES', flag: '🇪🇸', en: 'Spain', es: 'España' },
  { code: 'SE', flag: '🇸🇪', en: 'Sweden', es: 'Suecia' },
  { code: 'CH', flag: '🇨🇭', en: 'Switzerland', es: 'Suiza' },
  { code: 'TW', flag: '🇹🇼', en: 'Taiwan', es: 'Taiwán' },
  { code: 'TH', flag: '🇹🇭', en: 'Thailand', es: 'Tailandia' },
  { code: 'TN', flag: '🇹🇳', en: 'Tunisia', es: 'Túnez' },
  { code: 'TR', flag: '🇹🇷', en: 'Turkey', es: 'Turquía' },
  { code: 'UA', flag: '🇺🇦', en: 'Ukraine', es: 'Ucrania' },
  { code: 'AE', flag: '🇦🇪', en: 'United Arab Emirates', es: 'Emiratos Árabes' },
  { code: 'GB', flag: '🇬🇧', en: 'United Kingdom', es: 'Reino Unido' },
  { code: 'US', flag: '🇺🇸', en: 'United States', es: 'Estados Unidos' },
  { code: 'UY', flag: '🇺🇾', en: 'Uruguay', es: 'Uruguay' },
  { code: 'UZ', flag: '🇺🇿', en: 'Uzbekistan', es: 'Uzbekistán' },
  { code: 'VE', flag: '🇻🇪', en: 'Venezuela', es: 'Venezuela' },
  { code: 'VN', flag: '🇻🇳', en: 'Vietnam', es: 'Vietnam' },
];
