// Full homepage copy, bilingual (ES/EN). Editable by non-developers.
// Use **double asterisks** to make a fragment bold (rendered as <strong>).
// Lists are arrays of strings. Keys must match across both languages.

export const home = {
  en: {
    hero: {
      subtitle: 'Remember your frequency. Activate your inner Sun.',
      joinLine: 'Join the 144,000 Solar Codes.',
      intro: 'You are not here by accident. The Solar Code is calling you to remember who you truly are — a being of light, frequency, and cosmic purpose.',
      btnDiscover: 'Discover Your Solar Code',
      btnJoin: 'Join the 144,000',
      btnBegin: 'Begin the Solar Awakening',
    },
    whatIs: {
      title: 'What is The Solar Code?',
      subtitle: 'An inner technology of remembrance',
      quote: '"The Solar Code is the frequency of your soul in harmony with the universe."',
      p1: 'The Solar Code is **not a religion**. It is an inner technology of remembrance — a way to reconnect with your original frequency and cosmic purpose.',
      p2: 'Born from the convergence of **Mayan Science of Time** (Tzolk’in, the sacred 13:20 rhythm), **Ancient Chinese Cosmology** (the 5 Elements, the harmony of Heaven–Earth–Human, the Tao, and the vision of Datong), solar cosmology, and sacred geometry, The Solar Code reveals the vibrational blueprint of your existence.',
      p3: 'It is a map back to natural time, inner coherence, and the awakening of the 144,000 codes of light that will guide humanity into a new era of consciousness.',
    },
    codes: {
      title: 'The 144,000 Solar Codes',
      subtitle: 'A vibrational matrix of awakening',
      quote: '"When the 144,000 Solar Codes awaken in coherence, the human network lights up."',
      p1: 'The 144,000 Solar Codes form a vibrational matrix — a network of light frequencies that exist within the collective consciousness of humanity.',
      p2: 'Each person carries a unique Solar Code that reveals:',
      bullets: [
        'Your vibrational number (1–144,000)',
        'Your elemental nature (Earth, Water, Air, Fire, Ether)',
        'Your color frequency',
        'Your solar segment and cosmic position',
        'Your energetic function in the collective',
        'Your place in the solar network',
      ],
      closing: 'When enough codes awaken and activate in harmony, a threshold is crossed. The human network synchronizes. A new frequency emerges. This is the path to Datong — the Great Harmony.',
    },
    discover: {
      title: 'Discover Your Solar Code',
      subtitle: 'Calculate your unique frequency',
    },
    elements: {
      title: 'The 5 Universal Elements',
      subtitle: 'The building blocks of existence',
    },
    naturalTime: {
      title: 'Natural Time vs Mechanical Time',
      subtitle: 'Return to the rhythm of the cosmos',
      quote: '"Time is not money. Time is art."',
      p1: 'Modern humanity is trapped in mechanical time — a linear, artificial construct that disconnects us from natural rhythms and cosmic cycles.',
      p2: 'The Solar Code invites you to return to **natural time**:',
      bullets: [
        'The rhythm of the Sun and Moon',
        'The cycles of Venus and planetary alignments',
        'Solstices and Equinoxes',
        'Eclipses and cosmic gateways',
        "The Tzolk’in (13:20 sacred calendar)",
        'The pulse of your own breath and heartbeat',
      ],
      p3: 'When you align with natural time, you step out of the matrix of urgency and scarcity. You remember that time is not a resource to be consumed — it is a canvas for creation, a spiral of evolution, a sacred dance with the cosmos.',
    },
    activation: {
      title: 'Activation of The Solar Code',
      subtitle: 'Knowing your code is only the beginning',
      quote: '"Activating your Solar Code means cleaning the body, elevating the breath, purifying the blood and remembering that the light already lives within you."',
      p1: 'Real transformation happens when you activate your code through conscious practice and inner alignment.',
      practices: [
        { name: 'Conscious Breathing', description: 'Connect with your life force through intentional breath work' },
        { name: 'Meditation', description: 'Quiet the mind and tune into your inner frequency' },
        { name: 'Solar Practices', description: 'Align with the Sun through sunrise rituals and solar gazing' },
        { name: 'Clean Nutrition', description: 'Nourish your body with pure, living foods' },
        { name: 'Sauna & Purification', description: 'Release toxins and elevate your vibration' },
        { name: 'Grounding', description: 'Connect with Earth energy through barefoot walking' },
        { name: 'Sound & Mantra', description: 'Use sacred sound to activate your energy centers' },
        { name: 'Movement', description: 'Flow energy through conscious physical practice' },
        { name: 'Inner Coherence', description: 'Align heart, mind, and spirit in harmony' },
        { name: 'Choosing What Nourishes', description: 'Select experiences that elevate your frequency' },
      ],
    },
    dragon: {
      title: 'The Golden Dragon Path',
      subtitle: 'The solar archetype of transformation',
      quote: '"The Golden Dragon is not outside you. It is the solar force within you waiting to awaken."',
      p1: 'The Golden Dragon is the solar archetype of balance between spirit and matter, Heaven and Earth, inner fire and outer action.',
      listIntro: 'It represents:',
      bullets: [
        'Inner fire and vital force',
        'Transformation and transmutation',
        'Vertical ascension through the energy centers',
        'Balance between Heaven and Earth',
        'Awakening of the inner axis',
        'Service, wisdom, and coherence',
      ],
      p2: 'To walk the Golden Dragon Path is to activate your inner Sun, align your energy with cosmic purpose, and become a living bridge between the material and spiritual realms.',
    },
    solarGates: {
      title: 'The Solar Gates',
      subtitle: 'Cosmic moments of alignment',
      quote: '"The Solar Gates appear in the sky, but they only open within you."',
      p1: 'Throughout the year, the cosmos offers natural moments of alignment — **Solar Gates** — when the veil between dimensions thins and transformation becomes easier.',
      listIntro: 'These include:',
      bullets: [
        'Solstices (Summer and Winter)',
        'Equinoxes (Spring and Autumn)',
        'Eclipses (Solar and Lunar)',
        'Galactic Activation Portals',
        'New and Full Moons',
        'Planetary alignments',
      ],
      p2: 'These are sacred windows for meditation, cleansing, reset, setting intentions, and deepening your connection to cosmic consciousness. The gates are always there — but you must choose to walk through them.',
    },
    datong: {
      title: 'Datong — The Great Harmony',
      subtitle: 'The ultimate vision',
      quote: '"The Solar Code is a path toward Datong — the Great Harmony between Heaven, Earth and Human."',
      p1: '**Datong** (大同) is the ancient Chinese vision of the Great Harmony — a world where humanity lives in peace, love, wisdom, compassion, inner alignment, and cosmic order.',
      p2: 'It is not a utopia. It is not a distant dream. It is a **state of resonance** between humanity and the cosmos — a frequency that can be activated here and now, within each awakened soul.',
      p3: 'When the 144,000 Solar Codes awaken and align, Datong becomes possible. Not as a political system or external structure, but as an **inner reality** that radiates outward, transforming the collective field.',
      p4: 'This is the ultimate purpose of The Solar Code: to guide humanity back to harmony with itself, with nature, and with the cosmos.',
    },
    join: {
      title: 'Join the 144,000',
      subtitle: 'You are not here by accident',
      intro: 'If you feel this message, you may be one of the 144,000 Solar Codes awakening on Earth. Join the network. Remember your frequency. Activate your inner Sun.',
      benefits: [
        'Activation messages aligned with your Solar Code',
        'Updates on the 144,000 awakening movement',
        'Early access to new Solar Network features',
      ],
      name: 'Name',
      namePh: 'Your name',
      email: 'Email',
      emailPh: 'your@email.com',
      country: 'Country',
      countryPh: 'Your country',
      birthdate: 'Date of Birth',
      bdDay: 'Day', bdMonth: 'Month', bdYear: 'Year',
      months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
      message: 'Why do you feel called?',
      messagePh: 'Share what brought you here...',
      submit: 'Join the Solar Network',
      errFill: 'Please fill in required fields',
      success: 'Welcome to the Solar Network',
      successTitle: 'You are now part of the 144,000',
      successBody: 'Your frequency has been registered. The solar network has grown. We will be in touch as the activation unfolds.',
      error: 'Something went wrong. Please try again.',
    },
    ecosystem: {
      quote: 'First, the soul wakes up. Then, the solar network activates. Finally, humanity chooses a new direction.',
    },
    closing: {
      heading: 'You are not reading this by accident.',
      lines: [
        'You are remembering.',
        'Your Solar Code is already within you.',
        'Activate your inner Sun.',
        'Join the 144,000.',
        'Return to the Great Harmony.',
      ],
      button: 'Begin the Solar Awakening',
    },
  },

  es: {
    hero: {
      subtitle: 'Recuerda tu frecuencia. Activa tu Sol interior.',
      joinLine: 'Únete a los 144.000 Códigos Solares.',
      intro: 'No estás aquí por casualidad. El Código Solar te está llamando a recordar quién eres en verdad — un ser de luz, frecuencia y propósito cósmico.',
      btnDiscover: 'Descubre tu Código Solar',
      btnJoin: 'Únete a los 144.000',
      btnBegin: 'Comienza el Despertar Solar',
    },
    whatIs: {
      title: '¿Qué es The Solar Code?',
      subtitle: 'Una tecnología interior de recordación',
      quote: '"El Código Solar es la frecuencia de tu alma en armonía con el universo."',
      p1: 'The Solar Code **no es una religión**. Es una tecnología interior de recordación — una forma de reconectar con tu frecuencia original y tu propósito cósmico.',
      p2: 'Nacido de la convergencia entre la **Ciencia Maya del Tiempo** (el Tzolk’in, el sagrado ritmo 13:20), la **Cosmología China Antigua** (los 5 Elementos, la armonía Cielo–Tierra–Humano, el Tao y la visión de Datong), la cosmología solar y la geometría sagrada, The Solar Code revela el plano vibracional de tu existencia.',
      p3: 'Es un mapa de regreso al tiempo natural, a la coherencia interior y al despertar de los 144.000 códigos de luz que guiarán a la humanidad hacia una nueva era de consciencia.',
    },
    codes: {
      title: 'Los 144.000 Códigos Solares',
      subtitle: 'Una matriz vibracional de despertar',
      quote: '"Cuando los 144.000 Códigos Solares despiertan en coherencia, la red humana se enciende."',
      p1: 'Los 144.000 Códigos Solares forman una matriz vibracional — una red de frecuencias de luz que existen dentro de la consciencia colectiva de la humanidad.',
      p2: 'Cada persona porta un Código Solar único que revela:',
      bullets: [
        'Tu número vibracional (1–144.000)',
        'Tu naturaleza elemental (Tierra, Agua, Aire, Fuego, Éter)',
        'Tu frecuencia de color',
        'Tu segmento solar y posición cósmica',
        'Tu función energética en el colectivo',
        'Tu lugar en la red solar',
      ],
      closing: 'Cuando suficientes códigos despiertan y se activan en armonía, se cruza un umbral. La red humana se sincroniza. Emerge una nueva frecuencia. Este es el camino hacia Datong — la Gran Armonía.',
    },
    discover: {
      title: 'Descubre tu Código Solar',
      subtitle: 'Calcula tu frecuencia única',
    },
    elements: {
      title: 'Los 5 Elementos Universales',
      subtitle: 'Los pilares de la existencia',
    },
    naturalTime: {
      title: 'Tiempo Natural vs Tiempo Mecánico',
      subtitle: 'Regresa al ritmo del cosmos',
      quote: '"El tiempo no es dinero. El tiempo es arte."',
      p1: 'La humanidad moderna está atrapada en el tiempo mecánico — una construcción lineal y artificial que nos desconecta de los ritmos naturales y los ciclos cósmicos.',
      p2: 'El Código Solar te invita a regresar al **tiempo natural**:',
      bullets: [
        'El ritmo del Sol y la Luna',
        'Los ciclos de Venus y las alineaciones planetarias',
        'Solsticios y Equinoccios',
        'Eclipses y portales cósmicos',
        'El Tzolk’in (calendario sagrado 13:20)',
        'El pulso de tu propia respiración y latido',
      ],
      p3: 'Cuando te alineas con el tiempo natural, sales de la matriz de la urgencia y la escasez. Recuerdas que el tiempo no es un recurso para consumir — es un lienzo para crear, una espiral de evolución, una danza sagrada con el cosmos.',
    },
    activation: {
      title: 'Activación del Código Solar',
      subtitle: 'Conocer tu código es solo el comienzo',
      quote: '"Activar tu Código Solar significa limpiar el cuerpo, elevar la respiración, purificar la sangre y recordar que la luz ya vive dentro de ti."',
      p1: 'La verdadera transformación ocurre cuando activas tu código a través de la práctica consciente y la alineación interior.',
      practices: [
        { name: 'Respiración Consciente', description: 'Conecta con tu fuerza vital a través de la respiración intencional' },
        { name: 'Meditación', description: 'Aquieta la mente y sintoniza con tu frecuencia interior' },
        { name: 'Prácticas Solares', description: 'Alíneate con el Sol mediante rituales al amanecer y baños de sol' },
        { name: 'Nutrición Limpia', description: 'Nutre tu cuerpo con alimentos puros y vivos' },
        { name: 'Sauna y Purificación', description: 'Libera toxinas y eleva tu vibración' },
        { name: 'Enraizamiento', description: 'Conecta con la energía de la Tierra caminando descalzo' },
        { name: 'Sonido y Mantra', description: 'Usa el sonido sagrado para activar tus centros de energía' },
        { name: 'Movimiento', description: 'Haz fluir la energía con la práctica física consciente' },
        { name: 'Coherencia Interior', description: 'Alinea corazón, mente y espíritu en armonía' },
        { name: 'Elegir lo que Nutre', description: 'Escoge experiencias que eleven tu frecuencia' },
      ],
    },
    dragon: {
      title: 'El Camino del Dragón Dorado',
      subtitle: 'El arquetipo solar de la transformación',
      quote: '"El Dragón Dorado no está fuera de ti. Es la fuerza solar dentro de ti esperando despertar."',
      p1: 'El Dragón Dorado es el arquetipo solar del equilibrio entre espíritu y materia, Cielo y Tierra, fuego interior y acción exterior.',
      listIntro: 'Representa:',
      bullets: [
        'El fuego interior y la fuerza vital',
        'Transformación y transmutación',
        'Ascensión vertical a través de los centros de energía',
        'Equilibrio entre el Cielo y la Tierra',
        'El despertar del eje interior',
        'Servicio, sabiduría y coherencia',
      ],
      p2: 'Caminar el sendero del Dragón Dorado es activar tu Sol interior, alinear tu energía con el propósito cósmico y convertirte en un puente vivo entre lo material y lo espiritual.',
    },
    solarGates: {
      title: 'Las Puertas Solares',
      subtitle: 'Momentos cósmicos de alineación',
      quote: '"Las Puertas Solares aparecen en el cielo, pero solo se abren dentro de ti."',
      p1: 'A lo largo del año, el cosmos ofrece momentos naturales de alineación — **Puertas Solares** — cuando el velo entre dimensiones se adelgaza y la transformación se vuelve más fácil.',
      listIntro: 'Entre ellas:',
      bullets: [
        'Solsticios (Verano e Invierno)',
        'Equinoccios (Primavera y Otoño)',
        'Eclipses (Solares y Lunares)',
        'Portales de Activación Galáctica',
        'Lunas Nuevas y Llenas',
        'Alineaciones planetarias',
      ],
      p2: 'Son ventanas sagradas para meditar, limpiar, reiniciar, sembrar intenciones y profundizar tu conexión con la consciencia cósmica. Las puertas siempre están ahí — pero tú debes elegir atravesarlas.',
    },
    datong: {
      title: 'Datong — La Gran Armonía',
      subtitle: 'La visión última',
      quote: '"El Código Solar es un camino hacia Datong — la Gran Armonía entre Cielo, Tierra y Humano."',
      p1: '**Datong** (大同) es la antigua visión china de la Gran Armonía — un mundo donde la humanidad vive en paz, amor, sabiduría, compasión, alineación interior y orden cósmico.',
      p2: 'No es una utopía. No es un sueño lejano. Es un **estado de resonancia** entre la humanidad y el cosmos — una frecuencia que puede activarse aquí y ahora, dentro de cada alma despierta.',
      p3: 'Cuando los 144.000 Códigos Solares despiertan y se alinean, Datong se vuelve posible. No como un sistema político o una estructura externa, sino como una **realidad interior** que irradia hacia afuera, transformando el campo colectivo.',
      p4: 'Este es el propósito último del Código Solar: guiar a la humanidad de regreso a la armonía consigo misma, con la naturaleza y con el cosmos.',
    },
    join: {
      title: 'Únete a los 144.000',
      subtitle: 'No estás aquí por casualidad',
      intro: 'Si sientes este mensaje, puede que seas uno de los 144.000 Códigos Solares despertando en la Tierra. Únete a la red. Recuerda tu frecuencia. Activa tu Sol interior.',
      benefits: [
        'Mensajes de activación alineados con tu Código Solar',
        'Actualizaciones del movimiento de los 144.000',
        'Acceso anticipado a nuevas funciones de la Red Solar',
      ],
      name: 'Nombre',
      namePh: 'Tu nombre',
      email: 'Email',
      emailPh: 'tu@email.com',
      country: 'País',
      countryPh: 'Tu país',
      birthdate: 'Fecha de Nacimiento',
      bdDay: 'Día', bdMonth: 'Mes', bdYear: 'Año',
      months: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
      message: '¿Por qué te sientes llamado/a?',
      messagePh: 'Comparte lo que te trajo aquí...',
      submit: 'Unirme a la Red Solar',
      errFill: 'Por favor completa los campos requeridos',
      success: 'Bienvenido/a a la Red Solar',
      successTitle: 'Ya eres parte de los 144.000',
      successBody: 'Tu frecuencia ha sido registrada. La red solar ha crecido. Estaremos en contacto a medida que la activación se despliega.',
      error: 'Algo salió mal. Probá de nuevo.',
    },
    ecosystem: {
      quote: 'Primero, el alma despierta. Luego, la red solar se activa. Finalmente, la humanidad elige una nueva dirección.',
    },
    closing: {
      heading: 'No estás leyendo esto por casualidad.',
      lines: [
        'Estás recordando.',
        'Tu Código Solar ya está dentro de ti.',
        'Activa tu Sol interior.',
        'Únete a los 144.000.',
        'Regresa a la Gran Armonía.',
      ],
      button: 'Comienza el Despertar Solar',
    },
  },
};
