// The 60 Solar Tramos (segments) of the 144,000 matrix — Chapter 7 of the book.
// Each tramo = 2,400 codes. Element + color cycle every 5 tramos:
//   Earth/Red · Water/Blue · Air/White · Fire/Green · Ether/Gold.
// The element/color come from the TRAMO (i.e. the final Solar Code), NOT the Mayan seal.
//
// Content (energy name + description) is drafted from the book in the author's voice
// for the partner to refine. `tramos[i]` is tramo number i+1 (1..60).

// Tramo colors — distinct from the 4 Dreamspell seal colors. Keyed by element.
export const tramoColors = {
  earth: { en: { name: 'Red' }, es: { name: 'Rojo' }, hex: '#E23E3E' },
  water: { en: { name: 'Blue' }, es: { name: 'Azul' }, hex: '#3E6FE2' },
  air: { en: { name: 'White' }, es: { name: 'Blanco' }, hex: '#D8DCE6' },
  fire: { en: { name: 'Green' }, es: { name: 'Verde' }, hex: '#3FB97A' },
  ether: { en: { name: 'Gold' }, es: { name: 'Gold' }, hex: '#E2B83E' },
};
// Spanish gold label kept separate (book uses "Dorado").
tramoColors.ether.es.name = 'Dorado';

export const tramos = [
  { en: { energy: 'Root', description: 'Anchoring, order and firmness. The essential stability — the point of rootedness from which everything flowers.' }, es: { energy: 'Raíz', description: 'Anclaje, orden y firmeza. La estabilidad esencial: el punto de arraigo desde donde todo florece.' } },
  { en: { energy: 'Emotional Healing', description: 'An inner river that clears memories and releases unspoken pain, restoring balance to feeling.' }, es: { energy: 'Sanación Emocional', description: 'Un río interno que limpia memorias y libera el dolor no expresado, devolviendo el equilibrio al sentir.' } },
  { en: { energy: 'Prophetic Vision', description: 'An antenna-consciousness that sees beyond the horizon and reads the winds of time.' }, es: { energy: 'Visión Profética', description: 'Conciencia-antena que ve más allá del horizonte y sabe leer los vientos del tiempo.' } },
  { en: { energy: 'Awakening', description: 'The spark that begins the journey — a catalyst of change that ignites what lay dormant.' }, es: { energy: 'Despertar', description: 'La chispa que inicia el viaje: catalizador de cambios que enciende procesos dormidos.' } },
  { en: { energy: 'Unity', description: 'Communion with all that exists; they remember that we are parts of one field of consciousness and love.' }, es: { energy: 'Unidad', description: 'Comunión con todo lo que existe; recuerdan que somos partes de un mismo campo de conciencia y amor.' } },
  { en: { energy: 'Stability', description: 'Silent builders of the new world who anchor visions into lasting structures.' }, es: { energy: 'Estabilidad', description: 'Constructores silenciosos del nuevo mundo: anclan visiones en estructuras duraderas.' } },
  { en: { energy: 'Flow', description: 'They flow like springs, teaching how to yield without surrendering and flow without getting lost.' }, es: { energy: 'Fluidez', description: 'Fluyen como manantiales; enseñan a ceder sin rendirse y a fluir sin perderse.' } },
  { en: { energy: 'Clear Communication', description: 'Luminous, precise speech — translators of the language of light.' }, es: { energy: 'Comunicación Clara', description: 'Palabra luminosa y precisa: traductores del lenguaje de la luz.' } },
  { en: { energy: 'Courage', description: 'The fire of the inner hero — unafraid to decide or to fight for truth.' }, es: { energy: 'Coraje', description: 'El fuego del héroe interior: no temen decidir ni luchar por la verdad.' } },
  { en: { energy: 'Expanded Consciousness', description: 'A living quantum field; their presence connects to higher planes and expands inner space.' }, es: { energy: 'Conciencia Expandida', description: 'Campo cuántico vivo; su presencia conecta con planos superiores y expande el espacio interior.' } },
  { en: { energy: 'Nourishment', description: 'Fertile ground — wherever they arrive, something grows. Maternal energy in service of life.' }, es: { energy: 'Nutrición', description: 'Tierra fértil: donde llegan, algo crece. Energía maternal al servicio de la vida.' } },
  { en: { energy: 'Intuition', description: 'Deep listening that senses the unspoken and guides through sure feeling.' }, es: { energy: 'Intuición', description: 'Escucha profunda que siente lo que no se dice y guía a través de emociones certeras.' } },
  { en: { energy: 'Celestial Inspiration', description: 'They bring ideas like flashes of sky, turning the invisible into word and art.' }, es: { energy: 'Inspiración Celeste', description: 'Traen ideas como destellos de cielo y transforman lo invisible en palabra o arte.' } },
  { en: { energy: 'Transmutation', description: 'Alchemists of the soul: they burn pain and turn shadow into gold.' }, es: { energy: 'Transmutación', description: 'Alquimistas del alma: queman el dolor y convierten la sombra en oro.' } },
  { en: { energy: 'Cosmic Silence', description: 'Guardians of the fertile void; they radiate without speaking and calm without touching.' }, es: { energy: 'Silencio Cósmico', description: 'Guardianes del vacío fértil; irradian sin hablar y calman sin tocar.' } },
  { en: { energy: 'Structure', description: 'They embody the blueprint of the new Earth, materializing projects that join heaven and matter.' }, es: { energy: 'Estructura', description: 'Encarnan el plano de la nueva Tierra: materializan proyectos que unen cielo y materia.' } },
  { en: { energy: 'Rebirth', description: 'Emerging from the womb of the waters: they cleanse trauma and allow a fresh start.' }, es: { energy: 'Renacimiento', description: 'Emergen del útero de las aguas: limpian traumas y permiten empezar de nuevo.' } },
  { en: { energy: 'Language of Light', description: 'They do not speak, they transmit: their word heals, awakens and opens inner portals.' }, es: { energy: 'Lenguaje de Luz', description: 'No hablan, transmiten: su verbo sana, despierta y abre portales internos.' } },
  { en: { energy: 'Inner Phoenix', description: 'Those who return stronger; they know the art of being reborn from the ashes.' }, es: { energy: 'Fénix Interior', description: 'Los que vuelven más fuertes; conocen el arte de renacer desde las cenizas.' } },
  { en: { energy: 'Unified Field', description: 'Bridges between realities that hold the hidden weave of the universe.' }, es: { energy: 'Campo Unificado', description: 'Puentes entre realidades que sostienen el entramado oculto del universo.' } },
  { en: { energy: 'Legacy', description: 'Keepers of the ancestral seed: they embody the living message of their forebears.' }, es: { energy: 'Legado', description: 'Guardianes de la semilla ancestral: encarnan el mensaje vivo de sus antepasados.' } },
  { en: { energy: 'Sacred Cleansing', description: 'Living water that purifies spaces, relationships and subtle bodies.' }, es: { energy: 'Limpieza Sagrada', description: 'Agua viva que purifica ambientes, relaciones y cuerpos sutiles.' } },
  { en: { energy: 'Subtle Thought', description: 'They think with the heart — discerning without judging to open understanding.' }, es: { energy: 'Pensamiento Sutil', description: 'Piensan con el corazón: discernir sin juzgar para abrir el entendimiento.' } },
  { en: { energy: 'Solar Radiance', description: 'Emitters of light: warmth that comforts and a flame that awakens.' }, es: { energy: 'Radiación Solar', description: 'Emisores de luz: calor que reconforta y llama que despierta.' } },
  { en: { energy: 'Inner Tao', description: 'They move with the dance of non-doing; wherever they go, natural balance is restored.' }, es: { energy: 'Tao Interior', description: 'Vibran con la danza del no-hacer; donde van, se restablece el equilibrio natural.' } },
  { en: { energy: 'Ancestral Memory', description: 'Living libraries that honor the roots and bring them into the present.' }, es: { energy: 'Memoria Ancestral', description: 'Bibliotecas vivientes que honran las raíces y las traen al presente.' } },
  { en: { energy: 'Lucid Dream', description: 'Travelers between worlds; guardians of the dream plane who sow visions.' }, es: { energy: 'Sueño Lúcido', description: 'Viajeros entre mundos; guardianes del plano onírico que siembran visiones.' } },
  { en: { energy: 'Galactic Wisdom', description: 'They read the codes of the firmament and anchor them into daily life.' }, es: { energy: 'Sabiduría Galáctica', description: 'Leen los códigos del firmamento y los anclan en la vida cotidiana.' } },
  { en: { energy: 'Vibrational Justice', description: 'They do not judge, they harmonize: their fire does not burn, it purifies.' }, es: { energy: 'Justicia Vibral', description: 'No juzgan, armonizan: su fuego no quema, purifica.' } },
  { en: { energy: 'Christic Presence', description: 'Portals of compassion and coherence; their mere presence transforms.' }, es: { energy: 'Presencia Crística', description: 'Portales de compasión y coherencia; su sola presencia transforma.' } },
  { en: { energy: 'Silent Service', description: 'They act expecting nothing — the foundation no one sees yet everyone stands on.' }, es: { energy: 'Servicio Silencioso', description: 'Obran sin esperar nada: la base que nadie ve pero todos pisan.' } },
  { en: { energy: 'Feminine Holding', description: 'The womb of the collective soul: they embrace, nourish and hold without words.' }, es: { energy: 'Contención Femenina', description: 'Útero del alma colectiva: abrazan, nutren y contienen sin palabras.' } },
  { en: { energy: 'Self-Observation', description: 'Masters of the mirror: they teach you to look within with honesty and compassion.' }, es: { energy: 'Autoobservación', description: 'Maestros del espejo: enseñan a mirar hacia dentro con sinceridad y compasión.' } },
  { en: { energy: 'Kindled Word', description: 'Solar orators: their word does not inform, it transforms.' }, es: { energy: 'Palabra Encendida', description: 'Oradores solares: su palabra no informa, transforma.' } },
  { en: { energy: 'Zero Point', description: 'The power of non-action: guardians of the axis that unites all without judging anything.' }, es: { energy: 'Punto Cero', description: 'El poder del no-actuar: guardianes del eje que une todo sin juzgar nada.' } },
  { en: { energy: 'Vibrational Peace', description: 'When they arrive, the noise drops: they pacify spaces and reconcile polarities.' }, es: { energy: 'Paz Vibracional', description: 'Cuando llegan, baja el ruido: pacifican ambientes y reconcilian polaridades.' } },
  { en: { energy: 'Emotional Language', description: 'They translate emotion into bridges, saying what others only feel.' }, es: { energy: 'Lenguaje Emocional', description: 'Traducen emociones en puentes; dicen lo que otros sólo sienten.' } },
  { en: { energy: 'Codes of Light', description: 'They radiate galactic data that awakens dormant memories.' }, es: { energy: 'Códigos de Luz', description: 'Irradian datos galácticos que despiertan memorias dormidas.' } },
  { en: { energy: 'Solar Ray', description: 'Torches of the new time: they activate truth in those around them.' }, es: { energy: 'Rayo Solar', description: 'Antorchas del nuevo tiempo: activan la verdad en quienes los rodean.' } },
  { en: { energy: 'Sacred Geometry', description: 'They see order in chaos; each creation carries a harmonic proportion.' }, es: { energy: 'Geometría Sagrada', description: 'Ven el orden en el caos; cada creación suya porta una proporción armónica.' } },
  { en: { energy: 'Holding the Planet', description: 'Fixed points that stabilize planetary energy and sustain networks of light.' }, es: { energy: 'Sostén del Planeta', description: 'Puntos fijos que estabilizan la energía planetaria y sostienen redes de luz.' } },
  { en: { energy: 'Devotion', description: 'They give without conditions: water that gives without demanding presence.' }, es: { energy: 'Devoción', description: 'Entregan sin condiciones: agua que da sin reclamar presencia.' } },
  { en: { energy: 'Galactic Mirror', description: 'They reflect the forgotten parts of the soul; clarity from another dimension.' }, es: { energy: 'Espejo Galáctico', description: 'Reflejan las partes olvidadas del alma; claridad que llega de otra dimensión.' } },
  { en: { energy: 'Inner Thunder', description: 'Their presence shakes and their message awakens: a cosmic drum that calls the soul.' }, es: { energy: 'Trueno Interior', description: 'Su presencia sacude y su mensaje despierta: tambor cósmico que convoca al alma.' } },
  { en: { energy: 'Connection with the All', description: 'They perceive the web that links every atom; they sow unity and dissolve separation.' }, es: { energy: 'Conexión con el Todo', description: 'Perciben la red que une cada átomo; siembran unidad y disuelven la separación.' } },
  { en: { energy: 'Temple of Being', description: 'They honor the body as sacred: daily life as ceremony.' }, es: { energy: 'Templo del Ser', description: 'Honran el cuerpo como sagrado: la vida diaria como ceremonia.' } },
  { en: { energy: 'Emotional Channel', description: 'An antenna-like sensitivity that transmits messages from invisible dimensions.' }, es: { energy: 'Canal Emocional', description: 'Sensibilidad-antena que transmite mensajes desde dimensiones invisibles.' } },
  { en: { energy: 'Solar Consciousness', description: 'A crystalline mind aligned to the Central Sun: where there is confusion, they bring focus.' }, es: { energy: 'Conciencia Solar', description: 'Mente cristalina alineada al Sol Central: donde hay confusión, traen enfoque.' } },
  { en: { energy: 'Fire of Spirit', description: 'They carry a flame that does not consume but elevates: protectors of the fire of purpose.' }, es: { energy: 'Fuego del Espíritu', description: 'Portan una llama que no consume, eleva: protectores del fuego del propósito.' } },
  { en: { energy: 'Christic Consciousness', description: 'Living embodiments of compassionate love: their presence calms the chaos.' }, es: { energy: 'Conciencia Crística', description: 'Encarnaciones del amor compasivo: su presencia calma el caos.' } },
  { en: { energy: 'Guardians of the South', description: 'Like mountains: they sustain, observe and protect the sacred.' }, es: { energy: 'Guardianes del Sur', description: 'Como montañas: sostienen, observan y protegen lo sagrado.' } },
  { en: { energy: 'Lunar Ritual', description: 'They attune to the Moon and honor the biological and celestial rhythms.' }, es: { energy: 'Ritualidad Lunar', description: 'Sintonizan con la Luna y honran los ritmos biológicos y celestes.' } },
  { en: { energy: 'Inner Guidance', description: 'An inner beacon orients them; they teach others to trust their own compass.' }, es: { energy: 'Guía Interior', description: 'Un faro interno los orienta; enseñan a confiar en la propia brújula.' } },
  { en: { energy: 'Solar Dragon', description: 'They embody the fire that creates worlds: visionaries and keepers of the initiatic fires.' }, es: { energy: 'Dragón Solar', description: 'Encarnan el fuego que crea mundos: visionarios y guardianes de los fuegos iniciáticos.' } },
  { en: { energy: 'Light of the Source', description: 'They carry the spark of the Central Sun: reminding humanity of its stellar lineage.' }, es: { energy: 'Luz de la Fuente', description: 'Llevan la chispa del Sol Central: recuerdan a la humanidad su linaje estelar.' } },
  { en: { energy: 'Temple of Lineage', description: 'They safeguard the memory of humanity and restore the bond with forgotten wisdom.' }, es: { energy: 'Templo del Linaje', description: 'Resguardan la memoria de la humanidad y restauran el vínculo con la sabiduría olvidada.' } },
  { en: { energy: 'Tear of the Sun', description: "They weep the world's pain with compassion: their sensitivity is medicine." }, es: { energy: 'Lágrima del Sol', description: 'Lloran el dolor del mundo con compasión: su sensibilidad es medicina.' } },
  { en: { energy: 'Whisper of the Origin', description: 'They hear what others cannot; they awaken through questions more than answers.' }, es: { energy: 'Susurro del Origen', description: 'Escuchan lo que otros no pueden; despiertan con preguntas más que con respuestas.' } },
  { en: { energy: 'Flame of Ascension', description: 'They inspire letting go and rising: their flame is a stairway to higher planes.' }, es: { energy: 'Llama de la Ascensión', description: 'Inspiran a soltar y elevarse: su llama es escalera hacia planos superiores.' } },
  { en: { energy: 'Solar Crown', description: 'The last and the first: they carry the synthesis, silent light in service of the whole.' }, es: { energy: 'Corona Solar', description: 'El último y el primero: portan la síntesis, luz silenciosa al servicio de la totalidad.' } },
];
